apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app.kubernetes.io/name: "flink-kubernetes-operator"
  name: "flink"
  namespace: "flink"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  labels:
    app.kubernetes.io/name: "flink-kubernetes-operator"
  name: "flink"
  namespace: "flink"
roleRef:
  kind: "Role"
  name: "flink"
subjects:
  - kind: "ServiceAccount"
    name: "flink"
    namespace: "flink"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  labels:
    app.kubernetes.io/name: "flink-kubernetes-operator"
  name: "flink"
  namespace: "flink"
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "configmaps"
      - "pods/finalizers"
    verbs:
      - "*"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "deployments/finalizers"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"