apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink
  labels:
    app: flink
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - secrets
    verbs:
      - get
      - list