{
 "title": "Flink Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Jobs & Task Managers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs"
    }
   ]
  },
  {
   "title": "Registered Task Managers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  { "title": "Kafka Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_total",
     "legendFormat": "{{job_name}}-{{operator_name}}"
    }
   ]
  },
  {
   "title": "Consumption Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "No. of records / second" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate",
     "legendFormat": "{{job_name}}-{{operator_name}}"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInPerSecond",
     "legendFormat": "{{job_name}}-{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond",
     "legendFormat": "{{job_name}}-{{task_name}}"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "JobManager JVM CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManager JVM CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{tm_id}}__{{job}}"
    }
   ]
  },
  {
   "title": "JobManager JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}__used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Committed",
     "legendFormat": "{{host}}__committed"
    }
   ]
  },
  {
   "title": "TaskManager JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{tm_id}}__used"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Committed",
     "legendFormat": "{{tm_id}}__committed"
    }
   ]
  }
 ]
}