== Writing Queries

For information on how Flink SQL supports writing queries, please refer to the https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/overview/[upstream documentation].

=== Using secrets

You can use Kubernetes secrets with the Flink SQL Runner to provide security credentials to Flink job for connecting to the source or the target systems.
Secrets can be directly templated in the SQL statements with the following pattern:

[source,yaml]
----
{{secret:<NAMESPACE>/<SECRET NAME>/<DATA KEY>}}
----

=== Special Characters

Note that semicolon `+;+` is a special character used as a statement delimiter. If it's part of your SQL statements, make sure it is escaped by `+\\+`. 
For example, it might be used when specifying a `+properties.sasl.jaas.config+` value for a  Kafka connector configuration. 
In this case, it would look something like this:

[source,yaml]
----
'properties.sasl.jaas.config' = 'org.apache.flink.kafka.shaded.org.apache.kafka.common.security.plain.PlainLoginModule required username=\"test-user\" password=\"{{secret:flink/test-user/user.password}}\"\\;'
----

== Deploying a Flink SQL Query

Your SQL query can be submitted via the `+spec.job.args+` field of the `+FlinkDeployment+` custom resource.
It should be formed of a single string within an array literal (`+[ ]+`).
https://yaml-multiline.info/[Multi-line yaml strings] (using `+|+`,`+>+` characters) are not currently supported. 
However, newlines, tabs, and other whitespace characters within a single string are ignored, so queries can still be well-formatted.
See the example below for an illustration of the formatting.

.Example FlinkDeployment
[source,yaml]
----
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: standalone-etl
spec:
  image: quay.io/streamshub/flink-sql-runner:0.1.0
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/streamshub/flink-sql-runner.jar
    args: ["
        CREATE TABLE orders (
          order_number BIGINT, 
          price DECIMAL(32,2), 
          buyer ROW<first_name STRING, 
          last_name STRING>, 
          last_name STRING, 
          order_time TIMESTAMP(3)
        ) WITH (
          'connector' = 'datagen'
        ); 
        CREATE TABLE print_table 
        WITH (
          'connector' = 'print'
        ) 
        LIKE orders
        ; 
        INSERT INTO print_table 
          SELECT * 
          FROM orders;
        "]
    parallelism: 1
    upgradeMode: stateless
----