apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-cluster-role-binding
  namespace: flink
subjects:
  - kind: ServiceAccount
    name: flink
    namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink